twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals :
        categories: '@App\Repository\CategorieRepository'
        cartService: '@App\Cart\CartService'


when@test:
    twig:
        strict_variables: true
